[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "nft"

# Add Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# CORS headers for API functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Accept, Origin"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
